services:
  clamav-api:
    image: ghcr.io/devhatro/clamav-api:latest
    ports:
      - "8080:6000"
      - "9000:9000"
    environment:
      - GIN_MODE=release
      - CLAMAV_DEBUG=true
      - CLAMAV_SOCKET=/var/run/clamav/clamd.ctl
      - CLAMAV_MAX_SIZE=209715200
      - CLAMAV_HOST=0.0.0.0
      - CLAMAV_PORT=6000
      - CLAMAV_GRPC_PORT=9000
      - CLAMAV_ENABLE_GRPC=true
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:6000/api/health-check"]
      interval: 10s
      timeout: 5s
      retries: 18
      start_period: 90s
